home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name="home")
]

hospedes/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='hos_index'),
    path('hospedes/cadastro/', views.cad_hospedes, name='cad_hospedes'),
    path('hospedes/detalhes/<int:hospede_id>', views.hos_detalhes, name='hos_detalhes'),
    path('hospedes/editar/<int:hospede_id>', views.hos_editar, name='hos_editar'),
    path('hospedes/excluir/<int:hospede_id>', views.hos_excluir, name='hos_excluir'), 
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('contas.urls')),

#Essa parte de cima e do blog so apaga depois mais para frente
    path('', include('home.urls')),
    path('hospedes/', include('hospedes.urls')),
    path('quartos/', include('quartos.urls')),
    path('reservas/', include('reservas.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

reservas/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Hospedes(models.Model):
    nome = models.CharField(max_length=30)
    email= models.EmailField(max_length=100, blank=False, unique=True)
    data_nasci = models.DateField(auto_now=False, auto_now_add=False) #O formato padrão para armazenamento é "YYYY-MM-DD".
    cpf = models.CharField(max_length=11, unique=True)
    telefone = models.CharField(max_length=20)
    cidade = models.CharField(max_length=60)
    estado = models.CharField(max_length=40)
    
    def __str__(self):
        return self.nome
    
    class Meta:
      verbose_name_plural = "Hospedes"
    
class Quartos(models.Model):
    nome = models.CharField(max_length=30)
    numero = models.IntegerField(max_length=10)
    valor_diaria = models.FloatField(max_length=30)
    capacidade = models.IntegerField(max_length=10)
    descricao = models.TextField(max_length=150)
    ativo = models.BooleanField(default=True, blank=True, null=True)


    def __str__(self):
        return self.nome
    
    class Meta:
      verbose_name_plural = "Quartos"


class Reservas(models.Model):
    # nome = models.CharField(max_length=30)
    entrada_prevista = models.DateField(auto_now=False, auto_now_add=False) #O formato padrão para armazenamento é "YYYY-MM-DD".
    saida_prevista = models.DateField(auto_now=False, auto_now_add=False) #O formato padrão para armazenamento é "YYYY-MM-DD".
    # quarto_disponivel = models.CharField(max_length=40)
    valor_estadia = models.FloatField(max_length=30)
    numero_pessoas = models.IntegerField(max_length=10)
    hospedes = models.ForeignKey(Hospedes, on_delete=models.DO_NOTHING)
    quartos = models.ForeignKey(Quartos, on_delete=models.DO_NOTHING)
    

    def __str__(self):
            return self.nome
    
    class Meta:
      verbose_name_plural = "Reservas"

contas/forms.py
from typing import Any
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserForm(UserCreationForm):
    perfil = forms.ChoiceField(
        choices=[
            ("atendente", 'Atendente'),
            ("gerente", "Gerente"),
        ],
    )
    # imagem = forms.ImageField(required=False)
    # telefone = forms.CharField(max_length=9, required=False)

    class Meta: #Uma classe interna que fornece metadados ao formulário. 
        # Especifica quais campos do modelo User devem ser incluídos no formulário
        model = User
        fields = ['first_name', 'last_name', 'email',
                    'username', 'password1', 'password2']
        
    def clean(self):

        email = self.cleaned_data.get('email')
        # telefone = self.cleaned_data.get('telefone')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                'E-mail ja existe!'
            )

        # if len(telefone) < 9:
        #     self.add_error(
        #         'telefone',
        #         'telefone inválido!'
        #     )
        return super().clean()


class UserEditForm(UserCreationForm):
    perfil = forms.ChoiceField(
        choices=[
            ("atendente", 'Atendente'),
            ("gerente", "Gerente"),
        ],
    )
    last_password = forms.CharField(
        required=True,
        widget=forms.PasswordInput
    )
    imagem = forms.ImageField(required=False)
    telefone = forms.CharField(max_length=9, required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email',
                  'password1', 'password2']

hospedes/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from reservas.models import Hospedes
from django.db.models import Q
from datetime import datetime
from dateutil import parser
from django.utils import timezone
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
def index(request):
    hospede = Hospedes.objects.all()
    contexto={
        'hosp': hospede}
    return render(request, 'hospedes/index.html', contexto)

@login_required(login_url='login')
def cad_hospedes(request):
     
     if request.method == 'POST':
        nome = request.POST.get('nome')
        email= request.POST.get('email')
        data_nasci = request.POST.get('data_nasci')
        cpf = request.POST.get('cpf')
        telefone = request.POST.get('telefone') 
        cidade = request.POST.get('cidade')
        estado = request.POST.get('estado')

        if  nome == '' or  email=='' or  data_nasci=='' or cpf=='' or  telefone== '' or cidade=='' or  estado=='':
            messages.error(request, "Dados inválidos !")
            return render(request, 'hospedes/cadastro_hospedes.html')
        
        # data_nasci = datetime.strptime(data_nasci, '%d/%m/%Y').strftime('%Y-%m-%d')
        data_nasci = timezone.datetime.strptime(data_nasci, '%Y-%m-%d').date()

        if nome is None or len(nome) < 3 or nome.isspace():
            messages.error(request, "Muito curto!")
            return render(request,'hospedes/cadastro_hospedes.html')
        
        if cpf is None or len(cpf) < 11 or cpf.isspace():
            messages.error(request, "CPF inválido!")
            return render(request,'hospedes/cadastro_hospedes.html')
        
        if Hospedes.objects.filter(cpf=cpf).exists():
            messages.error(request, "CPF já cadastrado!")
            return render(request, 'hospedes/cadastro_hospedes.html')
        
        if Hospedes.objects.filter(email=email).exists():
            messages.error(request, "E-mail já cadastrado!")
            return render(request, 'hospedes/cadastro_hospedes.html')

        if telefone is None or len(telefone) < 10 or telefone.isspace():
            messages.error(request, "Telefone inválido!")
            return render(request,'hospedes/cadastro_hospedes.html')
        
        novo_hospede = Hospedes(nome=nome, email=email, data_nasci=data_nasci, cpf=cpf, telefone=telefone, cidade=cidade, estado=estado)
        novo_hospede.save()
        messages.success(request,"Hospede salvo com sucesso!")
        return redirect('hos_index')
     
     return render(request, 'hospedes/cadastro_hospedes.html')


@login_required(login_url='login')
def hos_detalhes(request, hospede_id):
    hospede = get_object_or_404(Hospedes, id=hospede_id)
    contexto={
        'hospede': hospede
    }
    return render(request, 'hospedes/detalhes_hospedes.html', contexto)


@login_required(login_url='login')
def hos_editar(request, hospede_id):
    hospede = get_object_or_404(Hospedes, pk=hospede_id)

    if request.method == 'POST':
        
        nome = request.POST.get('nome')
        email= request.POST.get('email')
        data_nasci = request.POST.get('data_nasci')
        cpf = request.POST.get('cpf')
        telefone = request.POST.get('telefone') 
        cidade = request.POST.get('cidade')
        estado = request.POST.get('estado')

        if  nome == '' or  email=='' or  data_nasci=='' or cpf=='' or  telefone== '' or cidade=='' or  estado=='':
            messages.error(request, "Dados inválidos !")
            return render(request, 'hospedes/cadastro_hospedes.html')
        
        # data_nasci = datetime.strptime(data_nasci, '%d/%m/%Y').strftime('%Y-%m-%d')
        data_nasci = timezone.datetime.strptime(data_nasci, '%Y-%m-%d').date()

        if nome is None or len(nome) < 3 or nome.isspace():
            messages.error(request, "Muito curto!")
            return render(request,'hospedes/cadastro_hospedes.html')
        
        if cpf is None or len(cpf) < 11 or cpf.isspace():
            messages.error(request, "CPF inválido!")
            return render(request,'hospedes/cadastro_hospedes.html')
        
        if Hospedes.objects.exclude(pk=hospede_id).filter(cpf=cpf).exists():
            messages.error(request, "CPF já cadastrado em outro hospede!")
            return render(request, 'hospedes/cadastro_hospedes.html')
        
        if Hospedes.objects.filter(email=email).exclude(pk=hospede_id).exists():
            messages.error(request, "E-mail já cadastrado!")
            return render(request, 'hospedes/cadastro_hospedes.html')

        if telefone is None or len(telefone) < 10 or telefone.isspace():
            messages.error(request, "Telefone inválido!")
            return render(request,'hospedes/cadastro_hospedes.html')
        hospede.nome = nome
        hospede.email = email
        hospede.data_nasci = data_nasci
        hospede.cpf = cpf
        hospede.telefone = telefone
        hospede.cidade = cidade
        hospede.estado = estado
        hospede.save()
        messages.success(request, "Hospede editado com sucesso!")
        return redirect('hos_index')
    return render(request, 'hospedes/editar_hospedes.html', {'hospede': hospede})


@login_required(login_url='login')
def hos_excluir(request, hospede_id):
    hospedes = get_object_or_404(Hospedes, pk=hospede_id)

    contexto = {
        'hospede': hospedes
    }

    if request.method == 'POST':
        hospedes.delete()
        messages.success(request, "Hospede deletado com sucesso!")
        return redirect('hos_index')
    return render(request, 'hospedes/del_hospedes.html', contexto)

hospedes/templates/hospedes/cadastro_hospedes.html
{% extends 'base_hotelaria.html' %}

{% load static %}

{% block title %} Hotelaria GTI{% endblock title %}

{% block titulo %} Cadastro {% endblock titulo %}

{% block conteudo %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="row mb-4">
      <div class="col-md-6">
        <div class="mb-3" style="text-align: left;">
          <label for="nome" class="form-label">Nome Completo*</label>
          <input type="text" class="form-control" id="nome" name="nome">
        </div>

        <div class="mb-3" style="text-align: left;">
          <label for="email" class="form-label">E-mail*</label>
          <input type="email" class="form-control" id="email" name="email">
        </div>

        <div class="mb-3"  style="text-align: left;">
          <label for="data_nasci" class="form-label">Data de Nascimento*</label>
          <input type="date" class="form-control" id="data_nasci" name="data_nasci">
        </div>

        <div class="mb-3" style="text-align: left;">
          <label for="estado" class="form-label">Estado*</label>
          <input type="text" class="form-control" id="estado" name="estado">
        </div>
      </div>

      <div class="col-md-6">
        <div class="mb-3" style="text-align: left;">
          <label for="cidade" class="form-label">Cidade*</label>
          <input type="text" class="form-control" id="cidade" name="cidade">
        </div>

        <div class="mb-3" style="text-align: left;">
          <label for="telefone" class="form-label">Telefone com DDD*</label>
          <input type="text" class="form-control" id="telefone" name="telefone">
        </div>

        <div class="mb-3" style="text-align: left;">
          <label for="cpf" class="form-label">CPF*</label>
          <input type="text" class="form-control" id="cpf" name="cpf">
        </div>
      </div>
    </div>

    <button class="w-25  btn btn-primary" type="submit">Salvar</button>
  </form>
{% endblock conteudo %}

hospedes/templates/hospedes/del_hospedes.html
{% extends 'base_hotelaria.html' %}
{% load static %}
{% block title %} Hotelaria GTI{% endblock title %}

{% block titulo %} Deletar Hospede {% endblock titulo %}

{% block conteudo %}
<div class="container mt-5">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6">
        <div class="mb-3">
          <label for="nome" class="form-label">Nome</label>
          <input type="text" name="nome" value="{{hospede.nome}}" class="form-control" id="nome" required disabled>
        </div>

        <div class="mb-3">
          <label for="email" class="form-label">E-mail</label>
          <input type="text" name="email" value="{{hospede.email}}" class="form-control" id="email"  required disabled>
        </div>
      </div>

      <div class="col-md-6">
        <div class="mb-3">
          <label for="data_nasci" class="form-label">Data de Nascimento</label>
          <input type="text" name="data_nasci" value="{{hospede.data_nasci}}" class="form-control" id="data_nasci"  required disabled>
        </div>

        <div class="mb-3">
          <label for="cpf" class="form-label">CPF</label>
          <input type="text" name="cpf" value="{{hospede.cpf}}" class="form-control" id="cpf"  required disabled>
        </div>
      </div>
    </div>

    <div class="mb-3">
      <label for="cidade" class="form-label">Cidade</label>
      <input type="text" name="cidade" value="{{hospede.cidade}}" class="form-control" id="cidade"  required disabled>
    </div>

    <div class="mb-3">
        <label for="estado" class="form-label">Estado</label>
        <input type="text" name="estado" value="{{hospede.estado}}" class="form-control" id="estado" required disabled>
      </div>

    <hr>
    <p class="p_excluir">Deseja realmente deletar o Hospede!?</p>
    <hr>
    <button type="submit" class="btn btn-primary">Deletar</button>
  </form>
  </div>
{% endblock conteudo %}

hospedes/templates/hospedes/detalhes_hospedes.html
{% extends 'base_hotelaria.html' %}
{% load static %}
{% block title %} Hotelaria GTI{% endblock title %}

{% block titulo %} Detalhes do Hospede {% endblock titulo %}

{% block conteudo %}
<div class="container mt-5">
  <div class="row d-flex">
    <div class="col-md-6">
      <div class="mb-3 p-3 bg-light shadow info-card" style='height: 90%;'>
        <h5>Nome</h5>
        <p id="nome">{{ hospede.nome }}</p>

        <h5>E-mail</h5>
        <p id="email">{{ hospede.email }}</p>

        <h5>Data de Nascimento</h5>
        <p id="data_nasci">{{ hospede.data_nasci }}</p>
      </div>
    </div>

    <div class="col-md-6">
      <div class="mb-3 p-3 bg-light shadow info-card" style='height: 90%;'>
        <h5>CPF</h5>
        <p id="cpf">{{ hospede.cpf }}</p>

        <h5>Telefone</h5>
        <p id="telefone">{{ hospede.telefone }}</p>

        <h5>Cidade</h5>
        <p id="cidade">{{ hospede.cidade }}</p>

        <h5>Estado</h5>
        <p id="estado">{{ hospede.estado }}</p>
      </div>
    </div>
  </div>
</div>
{% endblock conteudo %}

hospedes/templates/hospedes/editar_hospedes.html
{% extends 'base_hotelaria.html' %}

{% load static %}

{% block title %} Hotelaria GTI{% endblock title %}

{% block titulo %} Editar Hospede {% endblock titulo %}

{% block conteudo %}
  <form class="text-center mx-auto" method="post" enctype="multipart/form-data" >
    {% csrf_token %}

    <div class="row mb-4">
      <div class="col-md-6">
        <div class="mb-3" style="text-align: left;">
          <label for="id_nome" class="form-label">Nome Completo*</label>
          <input type="text" class="form-control" name="nome" value="{{ hospede.nome }}">
        </div>

        <div class="mb-3" style="text-align: left;">
          <label for="id_email" class="form-label">E-mail*</label>
          <input type="text" class="form-control" name="email" value="{{ hospede.email }}">
        </div>

        <div class="mb-3" style="text-align: left;">
            <label for="id_data_nasci" class="form-label">Data de Nascimento*</label>
            <input type="date" class="form-control" name="data_nasci" value="{{ hospede.data_nasci|date:'Y-m-d' }}">
        </div>

        <div class="mb-3" style="text-align: left;">
          <label for="id_estado" class="form-label">Estado*</label>
          <input type="text" class="form-control" name="estado" value="{{ hospede.estado }}">
        </div>
      </div>

      <div class="col-md-6">
        <div class="mb-3" style="text-align: left;">
          <label for="id_cidade" class="form-label">Cidade*</label>
          <input type="text" class="form-control" name="cidade" value="{{ hospede.cidade }}">
        </div>

        <div class="mb-3" style="text-align: left;">
          <label for="id_telefone" class="form-label">Telefone com DDD*</label>
          <input type="text" class="form-control" name="telefone" value="{{ hospede.telefone }}">
        </div>

        <div class="mb-3" style="text-align: left;">
            <label for="cpf" class="form-label">CPF*</label>
            <input type="text" class="form-control" name="cpf" value="{{ hospede.cpf }}">
        </div>
      </div>
    </div>

    <button class="w-50 btn btn-lg btn-primary" type="submit">Salvar Alterações</button>
    <a href="{% url 'hos_index' %}" class="mt-2 d-block">Cancelar</a>
  </form>
{% endblock conteudo %}

hospedes/templates/hospedes/index.html
{% extends 'base_hotelaria.html' %}
{% load static %}
{% block title %} Hotelaria GTI{% endblock title %}

{% block titulo %} Hospedes {% endblock titulo %}

{% block conteudo %}

<p><a href="{% url 'cad_hospedes' %}"><button class="btn btn-success" type="button"> <i class="fa-solid fa-user-plus" style="color: #fffafa;"></i> Novo Hospede</button></a></p>

        <div class="table-content table-responsive text-center">
              
                <table class="table table-hover">
                        <thead class="table-dark">
                                <tr>
                                        <th>NOME</th>
                                        <th>E-MAIL</th>
                                        <th>DATA DE NASCIMENTO</th>
                                        <th>CPF</th>
                                        <th>TELEFONE</th>
                                        <th>CIDADE</th>
                                        <th>ESTADO</th>
                                        <th colspan="3" class="text-md-center">OPERAÇÕES</th>
                                </tr>
                        </thead>
                        <tbody>
                                {% for hospede in hosp %}
                                <tr>
                                    <td>{{ hospede.nome }}</td>
                                    <td>{{ hospede.email }}</td>
                                    <td>{{ hospede.data_nasci }}</td>
                                    <td>{{ hospede.cpf }}</td>
                                    <td>{{ hospede.telefone }}</td>
                                    <td>{{ hospede.cidade}}</td>
                                    <td>{{ hospede.estado}}</td>

                                    <td><a href="{% url 'hos_detalhes' hospede.id %}"><button type="button" class="btn btn-primary btn-sm">Exibir</button></a></td>
                                    <td><a href="{% url 'hos_editar' hospede.id %}"><button type="button" class="btn btn-secondary btn-sm">Editar</button></a></td>
                                    <td><a href="{% url 'hos_excluir' hospede.id %}"><button type="button" class="btn btn-danger btn-sm">Remover</button></a>
                                
                                {% endfor %}
                                
                        </tbody>
                </table>
        
        </div>

{% endblock conteudo %}